sudo: required

services:
  - docker
# when tests will work
#language: ruby
#rvm:
#  - 2.3


 
install: gem install rails

script:
  - rm -rf .bundle vendor/bundle
  - export REPO=scalarm/scalarm_experiment_manager
  - docker build . -f Dockerfile -t $REPO
  - docker tag $REPO $REPO:tmp
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  -  docker push $REPO 
 

   
env:
  global:
   - secure: "pEoZWNrkDD2znOIxnbwr0TjHPmZLqdx1n3lO0UaTM+MU/dh2q5wpLZmPRPmA8Ewp4VjJN8j8o2p8NmfsycYmOuU00Xjbp2shq7/QkStUqKhm4GQRF3kQq373IcoB6LiDKsZkFomh9Jeis5roLiVwWoBl1dF4u2K2ySflmEOLPzsVMxrN0YKB4pJWiSsdGXT2bJxOy11MKYMPrJbJCz2TxjSBHV2nr39kc80RDMKWMuhk33UqCRg+KiumTlgw+lT7SRd6a8bQq2hDfKQD1fIJKgZ8NCGr/eGElWlpzZevnQuYAeVD7/LbEG4GdLEN/W0ULSXZHRqHvSgAkYjdMAzopoBkzofyUoFKCp2x9YtSGgBAVxUxHEVmZTGODbJKqf+jVrF8BtDch845QI7+Kc5M6ODvcrpQPG6ISr4vdxycYv4FP99iq/cIjlyp+TOTn5l2rjYJndlg3X7cF/CV7eLu1vr3QIagA/YdyR1cEg5MABuQRJVLeIpNL4jpo0eYNYl3HrM3mF/SZxKuzCNCjmQUjupQnWChKP7FCiihcIU7TaLOZ/foCyke5Vi3m5eoBuj01uqFDgJuccb/cciF8JsNQXSrCMuHDrcbyiQdjfjD885uBAaY6Ns2orrVk6A1NAG7UJ0XfpyVI/2Cohy9iRdde4CzYdcu0nnk+1i/x9FH1gQ="
   - secure: "LYb3+3DwEQ3BduI+oYEwSzI7pakchCdxEQC7DT/L9NmxaASDXOLRN3VFrBYoFE+/7tzs+IINdAxDkdKoELMvfO3BbXpx/2uH68/aYwBreAf8EtV3RbO7lmJT8vV0PXehrEBMA1VWKlzG4sW1Fg2VFj5SJzgLRbG7og6CN68Gcu3SU84DH1LDGPmsOmiumyU/C2fYE38QX66XXnULJSNms7rtB+17qiro12VToI0sBcH+X94aGGgSTptGxP1UlXDU3KuX3/MnYl+wp9zYzUMP6TV4Vjo7yQAZWyMDcxGAw3wxc+PGDnxr58nVW0PTMf9QkdvWEsTU876FmYEtdjDGmbCnloHVdk9TlfPGTglAiV/re3R/Q0J1dxvKGmDqK6NEz/gqhL1aLVYuAsC9n/X493p7iO5kODrOBxiCwrJRco10mJQNG89XOqKL8/oujWvEL51SutFdAxG3F75QEjidgQfUeP4e3IFeVaVTNXK/Xx/akbANtaCz5AqKI8uxrKl8AW2rHdmBFujatI1KBzoJLNDwnEtaZ5P9AorIhrlvWmEqUj0S+9JCuXtZfqgK3QqYyNCjXCV2JBGxyzfr+iCu1XnZb6ZhpFyvWPqpqpND0joUhqAYTDLugHUNKBCCTTagLtRLzExB4Q1SqJWiPu7JOwoXGyJ73NhcCMVN2DNOKu4="
 
