# at which port the service should listen
#information_service_url: scal2.mooo.com:11300
information_service_url: 149.156.10.32:26416
information_service_user: scalarm
information_service_pass: hidden
# mongo_activerecord config
db_name: 'scalarm_db'
